### ISSUE TITLE
Latest Update errors on Save Load

### ISSUE THREAD

**Issue by TheLoneTec** [RW-NodeTree/RW_ModularizationWeapon#3]
It happens with just bare minimum mods too. But here is my hugslib log anyway.

https://gist.github.com/HugsLibRecordKeeper/47d3acb0151dac54586fb091f41ea7b9

And here are the 2 main errors.

You need to provide working lists for the keys and values in order to be able to load such dictionary. label=targetPartsWithId
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
Verse.Scribe_Collections:Look<string, Verse.LocalTargetInfo> (System.Collections.Generic.Dictionary`2<string, Verse.LocalTargetInfo>&,string,Verse.LookMode,Verse.LookMode)
RW_ModularizationWeapon.CompModularizationWeapon:PostExposeData ()
(wrapper dynamic-method) Verse.ThingWithComps:Verse.ThingWithComps.ExposeData_Patch3 (Verse.ThingWithComps)
Verse.ScribeExtractor:SaveableFromNode<Verse.Thing> (System.Xml.XmlNode,object[])
Verse.Scribe_Deep:Look<Verse.Thing> (Verse.Thing&,bool,string,object[])
Verse.Scribe_Deep:Look<Verse.Thing> (Verse.Thing&,string,object[])
RW_NodeTree.NodeContainer:ExposeData ()
Verse.ScribeExtractor:SaveableFromNode<RW_NodeTree.NodeContainer> (System.Xml.XmlNode,object[])
Verse.Scribe_Deep:Look<RW_NodeTree.NodeContainer> (RW_NodeTree.NodeContainer&,bool,string,object[])
Verse.Scribe_Deep:Look<RW_NodeTree.NodeContainer> (RW_NodeTree.NodeContainer&,string,object[])
RW_NodeTree.CompChildNodeProccesser:PostExposeData ()
(wrapper dynamic-method) Verse.ThingWithComps:Verse.ThingWithComps.ExposeData_Patch3 (Verse.ThingWithComps)
Verse.ScribeExtractor:SaveableFromNode<Verse.ThingWithComps> (System.Xml.XmlNode,object[])
Verse.Scribe_Collections:Look<Verse.ThingWithComps> (System.Collections.Generic.List`1<Verse.ThingWithComps>&,bool,string,Verse.LookMode,object[])
Verse.ThingOwner`1<Verse.ThingWithComps>:ExposeData ()
Verse.ScribeExtractor:SaveableFromNode<Verse.ThingOwner`1<Verse.ThingWithComps>> (System.Xml.XmlNode,object[])
Verse.Scribe_Deep:Look<Verse.ThingOwner`1<Verse.ThingWithComps>> (Verse.ThingOwner`1<Verse.ThingWithComps>&,bool,string,object[])
Verse.Scribe_Deep:Look<Verse.ThingOwner`1<Verse.ThingWithComps>> (Verse.ThingOwner`1<Verse.ThingWithComps>&,string,object[])
Verse.Pawn_EquipmentTracker:ExposeData ()
Verse.ScribeExtractor:SaveableFromNode<Verse.Pawn_EquipmentTracker> (System.Xml.XmlNode,object[])
Verse.Scribe_Deep:Look<Verse.Pawn_EquipmentTracker> (Verse.Pawn_EquipmentTracker&,bool,string,object[])
Verse.Scribe_Deep:Look<Verse.Pawn_EquipmentTracker> (Verse.Pawn_EquipmentTracker&,string,object[])
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.ExposeData_Patch2 (Verse.Pawn)
Verse.ScribeExtractor:SaveableFromNode<Verse.Pawn> (System.Xml.XmlNode,object[])
Verse.Scribe_Collections:Look<Verse.Pawn> (System.Collections.Generic.List`1<Verse.Pawn>&,bool,string,Verse.LookMode,object[])
Verse.Scribe_Collections:Look<Verse.Pawn> (System.Collections.Generic.HashSet`1<Verse.Pawn>&,bool,string,Verse.LookMode)
Verse.Scribe_Collections:Look<Verse.Pawn> (System.Collections.Generic.HashSet`1<Verse.Pawn>&,string,Verse.LookMode)
RimWorld.Planet.WorldPawns:ExposeData ()
Verse.ScribeExtractor:SaveableFromNode<RimWorld.Planet.WorldPawns> (System.Xml.XmlNode,object[])
Verse.Scribe_Deep:Look<RimWorld.Planet.WorldPawns> (RimWorld.Planet.WorldPawns&,bool,string,object[])
Verse.Scribe_Deep:Look<RimWorld.Planet.WorldPawns> (RimWorld.Planet.WorldPawns&,string,object[])
RimWorld.Planet.World:ExposeComponents ()
(wrapper dynamic-method) RimWorld.Planet.WorldGenStep_Components:RimWorld.Planet.WorldGenStep_Components.GenerateFromScribe_Patch1 (RimWorld.Planet.WorldGenStep_Components,string)
(wrapper dynamic-method) RimWorld.Planet.WorldGenerator:RimWorld.Planet.WorldGenerator.GenerateFromScribe_Patch3 (string)
(wrapper dynamic-method) RimWorld.Planet.World:RimWorld.Planet.World.ExposeData_Patch1 (RimWorld.Planet.World)
(wrapper dynamic-method) Verse.Game:Verse.Game.LoadGame_Patch10 (Verse.Game)
(wrapper dynamic-method) Verse.SavedGameLoaderNow:Verse.SavedGameLoaderNow.LoadGameFromSaveFileNow_Patch1 (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

and

Cannot fill dictionary because there are no keys. label=targetPartsWithId
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
Verse.Scribe_Collections:Look<string, Verse.LocalTargetInfo> (System.Collections.Generic.Dictionary`2<string, Verse.LocalTargetInfo>&,string,Verse.LookMode,Verse.LookMode,System.Collections.Generic.List`1<string>&,System.Collections.Generic.List`1<Verse.LocalTargetInfo>&,bool)
Verse.Scribe_Collections:Look<string, Verse.LocalTargetInfo> (System.Collections.Generic.Dictionary`2<string, Verse.LocalTargetInfo>&,string,Verse.LookMode,Verse.LookMode)
RW_ModularizationWeapon.CompModularizationWeapon:PostExposeData ()
(wrapper dynamic-method) Verse.ThingWithComps:Verse.ThingWithComps.ExposeData_Patch3 (Verse.ThingWithComps)
(wrapper dynamic-method) Verse.CrossRefHandler:Verse.CrossRefHandler.ResolveAllCrossReferences_Patch1 (Verse.CrossRefHandler)
(wrapper dynamic-method) Verse.ScribeLoader:Verse.ScribeLoader.FinalizeLoading_Patch1 (Verse.ScribeLoader)
(wrapper dynamic-method) Verse.Game:Verse.Game.LoadGame_Patch10 (Verse.Game)
(wrapper dynamic-method) Verse.SavedGameLoaderNow:Verse.SavedGameLoaderNow.LoadGameFromSaveFileNow_Patch1 (string)
Verse.Root_Play/<>c:<Start>b__1_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by Cn-mjt44** [comment]
This is a loading probram of the save of old version mod to new version. I removed some unused data, that make this loading in different orders. So is not bugs if this is not append after you save and load.

**Comment by Cn-mjt44** [comment]
OK, I found it, thanks.

**Comment by TheLoneTec** [comment]
yup, was fixed, thanks!
